airpoms/airpoms/urls.py
from django.contrib import admin
from django.urls import path, include
from airpoms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('login/logout', views.LogoutView.as_view(), name='logout'),
    path('airpoms/about', views.AboutView.as_view(), name='about'),
    path('airpoms/map', views.MapView.as_view(), name='map'),
    path('airpoms/monitoredareas', views.MonitoredAreasList.as_view(), name='monitoredareas'),
    path('airpoms/monitoredareas/create', views.CreateMonitoredAreaView.as_view(), name='add-monitoredarea'),
    path('airpoms/area/<int:pk>', views.AreaView.as_view(), name='area'),
    path('airpoms/area/<int:pk>/session/create', views.CreateSessionView.as_view(), name='add-session'),
    path('airpoms/session/<int:pk>', views.SessionView.as_view(), name='session'),
    path('airpoms/session/<int:pk>/ajax', views.SessionDataAjax.as_view(), name='session-data'),
    path('airpoms/session/<int:pk>/drop_altitude', views.SessionDropAltitudeDataView.as_view(), name='session-drop-altitude'),
    path('airpoms/session/<int:pk>/graphs', views.SessionGraphsView.as_view(), name='session-graphs'),
    path('airpoms/session/<int:pk>/import', views.SessionImportDataView.as_view(), name='session-import-data'),
    path('airpoms/session/<int:pk>/import/ajax', views.SessionImportDataAjax.as_view(), name='session-import-ajax'),
    path('airpoms/session/<int:pk>/drop/selected', views.DropSelectedMeasurements.as_view(), name='session-drop-selected'),
    path('airpoms/session/<int:pk>/edit', views.EditSessionView.as_view(), name='session-edit'),
]

airpoms/airpoms/models.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "cheAria" in
# collaboration with FBK Junior
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.db.models import Max, Avg
from django.utils.translation import ugettext_lazy as _
from airpoms.utils import iaq_color


class Country(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    code = models.CharField(max_length=200, verbose_name=_("name"), unique=True)

    def __str__(self):
        return "%s (%s)" %(self.name, self.code)


    class Meta:
        verbose_name = _("Country")
        verbose_name_plural = _("Countries")
        ordering = ["name"]


class Region(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    country = models.ForeignKey(Country, verbose_name=_("country"), on_delete=models.CASCADE)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = _("Region")
        verbose_name_plural = _("Regions")
        ordering = ["country", "name"]


class Province(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    region = models.ForeignKey(Region, verbose_name=_("region"), on_delete=models.CASCADE)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = _("Province")
        verbose_name_plural = _("Provinces")
        ordering = ["region", "name"]


class City(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    province = models.ForeignKey(Province, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")
        ordering = ["province", "name"]


class Property(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    unit = models.CharField(max_length=200, null=True, blank=True, verbose_name=_("unit"))

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = _("Property")
        verbose_name_plural = _("Properties")
        ordering = ["name"]


class MonitoredArea(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name=_("city"))

    @property
    def latest_iaq(self):
        try:
            return self.measurement_set.order_by(
                "-date"
            )[0].session.measurementsessioncache_set.get(
                property__name="IAQ"
            )
        except (IndexError, AttributeError):
            return None

    def qualitycolor(self):
        if getattr(self, "latest_iaq"):
            return iaq_color(self.latest_iaq.value)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = _("Monitored area")
        verbose_name_plural = _("Monitored areas")
        ordering = ["name"]


class MeasurementSession(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("name"))
    area = models.ForeignKey(MonitoredArea, on_delete=models.CASCADE, verbose_name=_("area of monitoring"))
    notes = models.TextField(null=True, blank=True, verbose_name=_("annotations"))

    @property
    def maxaltitude(self):
        try:
            q = MeasurementValue.objects.filter(measurement__session=self)
            return q.filter(property__name="Altitude").aggregate(Max("value"))["value__max"]
        except Exception as e:
            return 0

    def lat_center(self):
        try:
            qs = MeasurementValue.objects.filter(measurement__session=self, property__name="Latitude")
            avglat = qs.aggregate(Avg("value"))["value__avg"]
        except:
            avglat = 0
        return avglat

    def long_center(self):
        try:
            qs = MeasurementValue.objects.filter(measurement__session=self, property__name="Longitude")
            avglong = qs.aggregate(Avg("value"))["value__avg"]
        except:
            avglong = 0
        return avglong

    @property
    def is_altitude_scanned(self):
        qs = MeasurementValue.objects.filter(measurement__session=self, property__name="Altitude")
        return qs.exists()


    def __str__(self):
        return "%s %s %s %s" % (_("Measurement session"), self.name, _("in"), self.area)


    class Meta:
        verbose_name = _("Measurement session")
        verbose_name_plural = _("Measurement sessions")
        ordering = ["area", "name"]


class Measurement(models.Model):
    area = models.ForeignKey(MonitoredArea, on_delete=models.CASCADE, verbose_name=_("area of monitoring"))
    session = models.ForeignKey(MeasurementSession, on_delete=models.CASCADE, verbose_name=_("measurement session"))
    date = models.DateTimeField(verbose_name=_("date and time of the measurement"))

    def qualitycolor(self):
        q = self.measurementvalue_set.filter(property__name="IAQ")
        if q.exists():
            return q[0].qualitycolor()
        return "#FFFFFF"

    def __str__(self):
        return "%s %s %s %s" % (_("Measurement of"), self.date.strftime("%d/%m/%Y %H:%M"), _("in"), self.area)


    class Meta:
        verbose_name = _("Measurement")
        verbose_name_plural = _("Measurements")
        ordering = ["area", "date"]


class MeasurementValue(models.Model):
    measurement = models.ForeignKey(Measurement, on_delete=models.CASCADE, verbose_name=_("measurement"))
    property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name=_("property"))
    value = models.FloatField(verbose_name=_("value"))

    def qualitycolor(self):
        if self.property.name == "IAQ":
            return iaq_color(self.value)

    def __str__(self):
        return "%s %s %s" %(self.property, _("of"), self.measurement)


    class Meta:
        verbose_name = _("Measurement value")
        verbose_name_plural = _("Measurements values")
        ordering = ["measurement", "property"]


# This model is intended to save caches of the measurements
# (for example, the average IRQ)
class MeasurementSessionCache(models.Model):
    session = models.ForeignKey(MeasurementSession, on_delete=models.CASCADE, verbose_name=_("measurement session"))
    property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name=_("property"))
    value = models.FloatField(verbose_name=_("value"))

    def __str__(self):
        return "%s %s %s" %(self.property, _("of"), self.session)


    class Meta:
        verbose_name = _("Measurement value cache")
        verbose_name_plural = _("Measurements values caches")
        ordering = ["session", "property"]

airpoms/airpoms/forms.py
# Copyright (c) 2018-2019 Marco Marinello <marco.marinello@school.rainerum.it>
# This code has been written for Rainerum Robotic's project "cheAria" in
# collaboration with FBK Junior
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django import forms
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': "form-control", "placeholder": _("Username")}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': "form-control", "placeholder": _("Password")}
        )
    )


class ImportForm(forms.Form):
    datatypes = [
        ["airpoms.csv", _("AirPoMS sensor comma separted value file (AIRPOMS.CSV)")],
        ["info.txt", _("FBK sensor built-in file (INFO.TXT)")],
    ]
    datatype = forms.ChoiceField(choices=datatypes, label=_("Data type"))
    file = forms.FileField(label=_("File"))
    altitude = forms.BooleanField(required=False, label=_("Import altitude data"))

airpoms/airpoms/templates/airpoms/area.html
{% extends "airpoms/base.html" %}{% load i18n static %}
{% block extrahead %}<script type="text/javascript" src="{% static 'js/jquery.flot.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flot.axislabels.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flot.time.js' %}"></script>
{% endblock %}
{% block title %}{{object.name}}{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="page-header">
      <h3>{{object.name}}</h3>
    </div>
  </div>
  <div class="col-lg-4">
    {% if perms.airpoms.add_measurementsession %}
    <a href="{% url 'add-session' pk=object.pk %}" class="btn btn-lg btn-block btn-primary">
      <i class="fas fa-plus-circle" aria-hidden="true"></i>
      {% trans "Create session" %}
    </a>
    {% endif %}
  </div>
</div>
<br>
<div id="graph1" style="height:250px;"></div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>{% trans "Session" %}</th>
      <th>{% trans "Date" %}</th>
      <th>{% trans "Average IAQ" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for m in measurements %}
    <tr>
      <td><i class="fas fa-circle" style="color: {{m.qualitycolor}}"></i></td>
      <td>{{m.session.name}}</td>
      <td>{{m.date}}</td>
      <td>{{m.iaq|floatformat:2}}</td>
      <td><a class="btn btn-lg btn-airpoms" href="{% url 'session' pk=m.session.pk %}">
        <i class="fas fa-arrow-right"></i>
      </a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
  var dx = [
    {% for m in measurements %}[{{m.jstimestamp|stringformat:"f"}}, {{m.iaq|stringformat:"f"}}], {% endfor %}
  ];
  $.plot("#graph1", [dx], {
    points: {show: true},
    lines: {show: true},
    xaxis: {mode: "time", axisLabel: "{% trans 'Date' %}"},
    yaxis: {axisLabel: "{% trans 'IAQ' %}"}
  });
</script>
{% endblock %}

airpoms/airpoms/templates/airpoms/areas.html
{% extends "airpoms/base.html" %}{% load i18n %}
{% block title %}{% trans "Monitored areas" %}{% endblock %}
{% block content %}
<div class="row">
  <div class="page-header col-lg-8">
    <h3>{% trans "List of the monitored areas" %}</h3>
  </div>
  <div class="col-lg-4">
    {% if perms.airpoms.add_monitoredarea %}
    <a href="{% url 'add-monitoredarea' %}" class="btn btn-lg btn-block btn-primary">
      <i class="fas fa-plus-circle" aria-hidden="true"></i>
      {% trans "Add monitored area" %}
    </a>
    {% endif %}
  </div>
</div>
<br>
<table class="table table-striped" id="areas">
  <thead>
    <tr>
      <th></th>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Location" %}</th>
      <th>{% trans "Measurements" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for i in object_list %}
    <tr>
      <td>{% if i.latest_iaq %}<i class="fas fa-circle" style="color: {{i.qualitycolor}}"></i>{% endif %}</td>
      <td>{{i.name}}</td>
      <td>{{i.city}} - {{i.city.province}} ({{i.city.province.region.country.code|upper}})</td>
      <td>{{i.measurement_set.all|length}}</td>
      <td>
        <a class="btn btn-lg btn-airpoms" href="{% url 'area' pk=i.pk %}">
          <i class="fas fa-arrow-right"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script type="text/javascript">
  $("#areas").DataTable({"order": [[1, "asc"]]});
</script>
{% endblock %}

airpoms/airpoms/templates/airpoms/base.html
{% extends "base.html" %}{% load static %}
{% block standardcontent %}
{% include "airpoms/navbar.html" %}
<div class="container-fluid pr-5 pl-5 mt-navbar">
  <div class="jumbotron mb-0">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
      {{message}}
      <i class="fas fa-times float-right btn" onclick="$(this).parent().slideUp();"></i>
    </div>
    {% endfor %}
    {% block content %}{% endblock content %}
  </div>
</div>
{% endblock standardcontent %}

airpoms/airpoms/templates/airpoms/dropselected.html
{% extends "airpoms/base.html" %}{% load i18n %}
{% block title %}{% trans "Drop selected measurements" %}{% endblock %}
{% block content %}

<h1>{% trans "Really drop the following measurements?" %}</h1>

<br><br>

<form action="" method="POST">
  <ul>
  {% for i in ms %}<li>{{i}} <input type="hidden" name="{{i.pk}}" value="del"></li>{% endfor %}
  </ul>
  <br><br>
  {% csrf_token %}
  <input type="hidden" name="dodelete" value="yes">
  <button type="submit" class="btn btn-lg btn-danger">{% trans "Yes, delete!" %}</button>
</form>

{% endblock %}

airpoms/airpoms/templates/airpoms/editsession.html
{% extends "airpoms/base.html" %}{% load i18n %}
{% block title %}{% trans "Session edit" %}{% endblock %}
{% block content %}

<h1>{% trans "Editing session" %} {{object.name}}</h1>

<br><br>

<form action="" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-lg btn-success">
    <i class="fas fa-save"></i>
    {% trans "Save" %}
  </button>
</form>

{% endblock %}

airpoms/airpoms/templates/airpoms/importer.html
{% extends "airpoms/base.html" %}{% load i18n %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="modal" tabindex="-1" role="dialog" id="pgmodal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Importing in progress" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <br>
        <p id="status"></p>
        <br>
        <div class="progress">
          <div id="pgbar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="col-lg-8">
  <div class="page-header">
    <h3>{{title}}</h3>
  </div>
</div>
<br>

<form enctype="multipart/form-data" id="form" onsubmit="return false;">{% csrf_token %}
  <table class="table">
    <tbody>
      {{form.as_table}}
    </tbody>
  </table>
  <button class="btn btn-lg {{btn}}" role="button" id="run_import">
    <i class="fas {{fa}}" aria-hidden="true"></i>
    {{submit_text}}
  </button>
</form>

<script type="text/javascript">
  $("select").each(function (i) {
    $(this).addClass("form-control").select2();
  });
  $("input").each(function(i) {
    var type = $(this).attr("type");
    if (type != "checkbox" && type != "file") $(this).addClass("form-control");
  });

  function setPgBar(id, perc) {
    perc = perc.toString() + "%";
    $(id).attr("aria-valuenow", perc).width(perc);
  }


  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
    }
  });

  $("#run_import").click(function () {
    $("#pgmodal").modal();
    var formData = new FormData();
    formData.append("file", $("#id_file")[0].files[0]);
    formData.append("csrfmiddlewaretoken", $("input[name='csrfmiddlewaretoken']").val());
    formData.append("datatype", $("#id_datatype").val());
    formData.append("altitude", $("#id_altitude").is(":checked"));
    $.post({
      url: "{% url 'session-import-ajax' pk=pk %}",
      data: formData,
      processData: false,
      contentType: false,
      cache: false,
      xhrFields: {
        onprogress: function (e) {
          var all = e.currentTarget.response.split("\n");
          if (all.length < 2) return;
          line = all[all.length-2];
          console.log(line);
          if (!line || line == "") return;
          var vals = JSON.parse(line);
          setPgBar("#pgbar", vals["perc"]);
          $("#status").text(vals["status"]);
          if (vals["do_redirect"]) {location.href="{% url 'session' pk=pk %}";}
        }
      }
    });
  });
</script>
{% endblock %}

airpoms/airpoms/templates/airpoms/session.html
{% extends "airpoms/base.html" %}{% load i18n static querysets %}
{% block extrahead %}<link rel="stylesheet" href="{% static 'css/leaflet.css' %}">
<script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flot.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flot.axislabels.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.flot.time.js' %}"></script>
{% endblock %}
{% block title %}{{object.name}}{% endblock %}
{% block content %}

<!-- legend modal -->
<div class="modal" id="legend" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans "Legend" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="{% trans 'Close' %}">
          <span aria-hidden="true"><i class="fas fa-times"></i></span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="text-align: center;">{% trans "Color" %}</th>
              <th style="text-align: center;">{% trans "IAQ" %}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #219807;" aria-hidden="true"></i></td>
              <td> &le; 50 </td>
            </tr>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #B0D502;" aria-hidden="true"></i></td>
              <td> 50 &lt; x &le; 100 </td>
            </tr>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #FCE202;" aria-hidden="true"></i></td>
              <td> 100 &lt; x &le; 150 </td>
            </tr>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #FB8801;" aria-hidden="true"></i></td>
              <td> 150 &lt; x &le; 200 </td>
            </tr>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #CA0C73;" aria-hidden="true"></i></td>
              <td> 200 &lt; x &le; 300 </td>
            </tr>
            <tr>
              <td style="text-align: center;"><i class="fas fa-circle" style="color: #5B0187;" aria-hidden="true"></i></td>
              <td> &gt; 300 </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- end modal -->

<div class="row">
<div class="page-header col-lg-10">
  <h3>{{object.name}} (<a href='{% url "area" pk=object.area.pk %}' class="badge badge-primary">{{object.area}}</a>)</h3>
  {{object.notes|default:""}}
</div>
<div class="col-lg-2" style="text-align:right;">
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#legend">
    <i class="fas fa-sticky-note" aria-hidden="true"></i>
    {% trans "Legend" %}
  </button>
</div>
</div>

<br>

<div class="row">
  <div class="col-lg-12">
    <div id="map"></div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-1"></div>
  <div class="col-lg-2">
    <a href='{% url "session-edit" pk=object.pk %}' class="btn btn-lg btn-block btn-info">
      <i class="fas fa-edit" aria-hidden="true"></i>
      {% trans "Edit" %}
    </a>
  </div>
  <div class="col-lg-2">
    {% if perms.airpoms.add_measurement %}
    <a href='{% url "session-import-data" pk=object.pk %}' class="btn btn-lg btn-block btn-warning">
      <i class="fas fa-cloud-upload-alt" aria-hidden="true"></i>
      {% trans "Import" %}
    </a>
    {% endif %}
  </div>
  <div class="col-lg-2">
    <a href='{% url "session-graphs" pk=object.pk %}' class="btn btn-lg btn-block btn-primary">
      <i class="fas fa-chart-bar" aria-hidden="true"></i>
      {% trans "Graphs" %}
    </a>
  </div>
  <div class="col-lg-3">
    {% if perms.airpoms.delete_measurementvalue %}
    <a href='{% url "session-drop-altitude" pk=object.pk %}' class="btn btn-lg btn-block btn-danger">
      <i class="fas fa-trash" aria-hidden="true"></i>
      {% trans "Drop altitude data" %}
    </a>
    {% endif %}
  </div>
  <div class="col-lg-2">
    {% if perms.airpoms.delete_measurementvalue %}
    <a href='' id="do_drop_selected" class="btn btn-lg btn-block btn-danger" onclick="return false;">
      <i class="fas fa-trash" aria-hidden="true"></i>
      {% trans "Drop selected" %}
    </a>
    {% endif %}
  </div>
</div>
<br>
<form action="" method="POST" id="tabform">
<table class="table" id="measurements_table">
  <thead>
    <tr>
      <th>
        <input type="checkbox" id="checkall">
      </th>
      <th>{% trans "Date" %}</th>
      {% for i in object.measurement_set.all.0.measurementvalue_set.all %}
      <th>{% trans i.property.name %}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody id="measurements_tbody">
  </tbody>
</table>
{% csrf_token %}
</form>

<script type="text/javascript">
$(document).ready(function () {
  document.map = L.map('map').setView([{{object.lat_center|stringformat:"f"|default:"46"}}, {{object.long_center|stringformat:"f"|default:"11"}}], 16);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
		maxZoom: 22,
		attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
	}).addTo(document.map);

  $("#map").height($(window).height()-215);
  document.map.invalidateSize();
  // compile a DIY translation Array
  document._ = {
    {% for i in object.measurement_set.all.0.measurementvalue_set.all %}"{{i.property.name}}": "{% trans i.property.name %}",{% endfor %}
  }
  document.parsed_table_data = [];
  document.analyzed_values = ["IAQ"];
  document.dataset = {};
  for (i in document.analyzed_values) document.dataset[document.analyzed_values[i]] = {label: document.analyzed_values[i], data: []};
  document.last_altitude = 20+{{object.maxaltitude|stringformat:"f"|default:"0"}};

  $.ajax({
    type: "GET",
    url: "{% url 'session-data' pk=object.pk %}",
    processData: false,
    contentType: false,
    xhrFields: {
      onprogress: function (e) {
        var all = e.currentTarget.response.split("\n");
        for (var i in all) {
          var current = all[i];
          if (!document.parsed_table_data.includes(current) && current != "") {
            var table = JSON.parse(current);
            var popupText = "";
            $("#measurements_tbody").append("<tr>");
            $("#measurements_tbody").append("<td><input type='checkbox' name='"+table["id_norender"]+"'></td>");
            for (var att in table) {
              if (!att.includes("norender")) {
                $("#measurements_tbody").append("<td>" + table[att][0] + " " + table[att][1] +"</td>");
                if (att == "Date") popupText += table[att][0] + "<br>";
                else popupText += "<b>" + document._[att] + ":</b> " + table[att][0] + " " + table[att][1] + "<br>";
              }
            }
            $("#measurements_tbody").append("</tr>");
            if ("Altitude" in table) {
              var alt = 10+{{object.maxaltitude|stringformat:"f"}}-table["Altitude"][0];
              if (alt < document.last_altitude) {
                L.circle(
                  [table["Latitude"][0], table["Longitude"][0]],
                  {"color": table["qc_norender"], "fillColor": table["qc_norender"], "fillOpacity": 0.55, "radius": alt}
                ).addTo(document.map).bindPopup(popupText);
                document.last_altitude = alt;
              }
            }
            else {
              L.circle(
                [table["Latitude"][0], table["Longitude"][0]],
                {"color": table["qc_norender"], "fillColor": table["qc_norender"], "fillOpacity": 0.55, "radius": 10}
              ).addTo(document.map).bindPopup(popupText);
            }
            // push current to the history
            document.parsed_table_data.push(all[i]);
          }
        }
      }
    }
  });
});

$("#do_drop_selected").click(function () {
  $("#tabform").attr("action", "{% url "session-drop-selected" pk=object.pk %}");
  $("#tabform").submit();
});

$("#checkall").click(function() {
  $('input:checkbox').prop('checked', this.checked);
});

</script>

{% endblock %}